# Generated by Django 4.2 on 2023-04-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/Y%-m%-d%'),
        ),
    ]
